import { Category } from "../objects/category";

export const photoOfTheDay = {
  id: 99,
  img: "/images/dog.png",
  title: "Samurai King Resting",
  category: "Pets",
  price: 10000.0,
  isPremium: true,
  description:
    "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely scrambled part of Cicero's De Finibus in order to provide placeholder text to mockup various fonts for a type specimen book. So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely scrambled part of Cicero's De Finibus in order to provide placeholder text to mockup various fonts for a type specimen book. So how did the classical Latin become so incoherent? According to McClintock.",
};

export const cardObject = [
  {
    img: "/images/people.png",
    category: "People",
    title: "Red Bench",
    price: 3.86,
    isPremium: true,
    id: crypto.randomUUID(),
  },
  {
    img: "/images/man.png",
    category: "People",
    title: "Man",
    price: 100.0,
    isPremium: true,
    id: crypto.randomUUID(),
  },
  {
    img: "/images/landmarks.png",
    category: "Landmarks",
    title: "Architecture",
    price: 101.0,
    id: crypto.randomUUID(),
  },
  {
    img: "/images/food.png",
    category: "Food",
    title: "Egg Balloon",
    price: 93.89,
    id: crypto.randomUUID(),
  },
  {
    img: "/images/people.png",
    category: "People",
    title: "Red Bench",
    price: 3.86,
    id: crypto.randomUUID(),
    isPremium: true,
  },
  {
    img: "/images/man.png",
    category: "People",
    title: "Man",
    price: 100.0,
    id: crypto.randomUUID(),
  },
  {
    img: "/images/landmarks.png",
    category: "Landmarks",
    title: "Architecture",
    id: crypto.randomUUID(),
    price: 101.0,
  },
  {
    img: "/images/food.png",
    category: "Food",
    title: "Egg Balloon",
    price: 93.89,
    id: crypto.randomUUID(),
  },
  {
    img: "/images/people.png",
    category: "People",
    title: "Red Bench",
    price: 3.86,
    id: crypto.randomUUID(),
  },
  {
    img: "/images/man.png",
    category: "People",
    title: "Man",
    price: 100.0,
    id: crypto.randomUUID(),
  },
  {
    img: "/images/landmarks.png",
    category: "Landmarks",
    title: "Architecture",
    isPremium: true,
    id: crypto.randomUUID(),
    price: 101.0,
  },
  {
    img: "/images/food.png",
    category: "Food",
    title: "Egg Balloon",
    isPremium: true,
    id: crypto.randomUUID(),
    price: 93.89,
  },
  {
    img: "/images/people.png",
    category: "People",
    title: "Red Bench",
    id: crypto.randomUUID(),
    price: 3.86,
  },
  {
    img: "/images/man.png",
    category: "People",
    title: "Man",
    price: 100.0,
    isPremium: true,
    id: crypto.randomUUID(),
  },
  {
    img: "/images/landmarks.png",
    category: "Landmarks",
    id: crypto.randomUUID(),
    title: "Architecture",
    price: 101.0,
  },
  {
    img: "/images/food.png",
    category: "Food",
    title: "Egg Balloon",
    id: crypto.randomUUID(),
    isPremium: true,
    price: 93.89,
  },
];
